---
title: "hypo"
author: "Yihao Song(Allen)"
date: "2017???5???15???"
output: html_document
---
```{r}
# one sample two tailed t test mean
sample <- c(1:50)
sample <- 20 * ((sample - mean(sample))/sqrt(var(sample))) + 295
# mean(sample)
# var(sample)
t.test(x = sample, mu = 300)
```

```{r}
# one sample one tailed t test mean
# Null hypothesis: µ >= 110 
# Alternative hypothesis: µ < 110
library(pwr)
sample1 <- c(1:20)
sample1 <- 10 * ((sample1 - mean(sample1))/sqrt(var(sample1))) + 108
t.test(x = sample1, alternative = "less", mu = 110, conf.level = 0.99)
```

```{r}
# unpaired two samples two tailed t test mean
c1 <- c(1:30)
c2 <- c(1:25)
c1 <- 10 * ((c1 - mean(c1))/sqrt(var(c1))) + 78
c2 <- 15 * ((c2 - mean(c2))/sqrt(var(c2))) + 85
t.test(x = c1, y = c2, mu = 0, conf.level = 0.9)
```

```{r}
# unpaired two samples one tailed t test mean
c1 <- c(1:100)
c2 <- c(1:100)
c2 <- 20 * ((c1 - mean(c1))/sqrt(var(c1))) + 190
c1 <- 40 * ((c2 - mean(c2))/sqrt(var(c2))) + 200
t.test(x = c1, y = c2, alternative = "less", mu = 7, conf.level = 0.95)
```

```{r}
# paired sample two tailed t test mean
x <- c(95, 89, 76, 92, 91, 53, 67, 88, 75, 85, 90,
        85, 87, 85, 85, 68, 81, 84, 71, 46, 75, 80)
y <- c(90, 85,73,90,90,53,68,90,78,89,95,83,83,83,
       82,65,79,83,60,47,77,83)
t.test(x = x, y = y, mu = 0, paired = TRUE, conf.level = 0.95)
```


```{r}
# one sample two tailed proportion test 
prop.test(x = c(73), n = c(100), p = c(0.8), conf.level = 0.95)
```

