---
title: "homework4_4"
author: "syh"
date: "June 1, 2017"
output: pdf_document
---

```{r}
# in this section, we are gonna try to build random forest
# also, we would like to use grid search to find optimal parameters
```

```{r}
# read all data (train + prediction) without missing value
real_all_data <- read.csv(file = "H:/kaggle/houseprice/data/real_all_data_hybrid.csv",
                          stringsAsFactors = FALSE)[,-c(1,2)]
```

```{r}
# transform sale price to log sale price
real_all_data[,"SalePrice"] <- log(real_all_data[,"SalePrice"])
```

```{r}
# we would like to train a linear regression model with regulation
# 1. convert categorical ones to factors
for(i in 1:dim(real_all_data)[2]){
  if(is.character(real_all_data[,i])){
    real_all_data[,i] <- as.factor(real_all_data[,i])
  }
}
```

```{r}
# 1. split all data into train and prediction

model_data <- real_all_data[1:1460,]

pre_x <- real_all_data[-c(1:1460),]

# 2. split model data into train and test
set.seed(1000)
train_ind <- sample(1:dim(model_data)[1], size = dim(model_data)[1] * 0.7)

train_data <- model_data[train_ind,]
test_data <- model_data[-train_ind,]
```


```{r}
# train a random forest
library(randomForest)

sse <- Inf
opt_rf <- NULL

formula <- "SalePrice ~. - SalePrice"
# parameters ntree, mtry, nodesize
for(i in 1:100){
  
  seed <- sample.int(10000, 1)
  set.seed(seed)
  rf <- randomForest(formula = as.formula(formula), data = train_data, 
                     importance = TRUE, 
                     ntree = sample(x = c(100,200), 1),
                     mtry = sample(x = c(2:8), size = 1),
                     nodesize = sample(c(10,20,30,40),1)
                     )
  est_test_sp <- predict(object = rf, newdata = test_data)
  tmp_sse <- sum((est_test_sp - test_data[,"SalePrice"]) ^ 2)
  
  if(see > tmp_sse){
    see <- tmp_sse
    opt_rf <- rf
  }
  
}

```

```{r}
# have a look at this random forest
opt_rf
```

```{r}
plot(opt_rf)
# about 100 trees, error become relatively constant
```

```{r}
# have a look at importance of features
varImpPlot(x = opt_rf)
# from graph below, we find these important features are same with ones used in rpart
```

```{r}
# importacne
opt_rf$importance[order(-opt_rf$importance[,"%IncMSE"]),]
```


```{r}
# use partialPlot to check each features against saleprice
name_order <- order(-opt_rf$importance[,"%IncMSE"])

fea_name <- rownames(opt_rf$importance)[name_order]

for(name in fea_name[1:10]){
  
  partialPlot(x = opt_rf, pred.data = train_data, 
              x.var = eval(name), which.class = T,
              xlab = name, ylab = "Sale Price")
}
```


```{r}
# make prediction
pre_sale_price <- predict(object = rf, newdata = pre_x)
result <- data.frame(Id = c(1461:2919), SalePrice = exp(pre_sale_price))
write.csv(x = result, file = "H:/kaggle/houseprice/data/submission_6.csv",
          row.names = FALSE)
# Your submission scored 0.14541, not good.
```


